# Generated by Django 3.0 on 2020-12-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201228_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_history',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
